@baseUrl = http://localhost:3000/api

### 1. ĐĂNG KÝ TÀI KHOẢN MỚI
# Sau khi chạy xong cái này, ông nhớ vào MongoDB Compass đổi role: "admin" để test các quyền cao hơn nhé.
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "fullName": "Han Hari",
    "email": "hanhari@gmail.com",
    "password": "123123"
}

### -----------------------------------------------------------

### 2. ĐĂNG NHẬP
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "hanhari@gmail.com",
    "password": "123123"
}

### -----------------------------------------------------------

### 3. LẤY THÔNG TIN CÁ NHÂN (TEST TOKEN)
# Biến {{login.response.body.token}} sẽ tự động bốc token từ kết quả hàm login ở trên (nếu ông dùng REST Client)
# Nếu không, ông chỉ cần copy token dán đè vào chữ <DÁN_TOKEN_VÀO_ĐÂY>
@token = {{login.response.body.token}}

GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}